### ISSUE TITLE
pltsql_curr_compile_body_lineno multiple definition error

### ISSUE THREAD

**Issue by bachpro900** [babelfish-for-postgresql/babelfish_extensions#1978]
Hello,

When trying to install on Debian 11 (I replaced libicu66 with libicu67, and openjdk-8-jre with openjdk-9-jre), I am facing this problem:

```
c/tsql_analyze.o src/linked_servers.o src/pltsql_bulkcopy.o -L/opt/babelfish/lib    -Wl,--as-needed -Wl,-rpath,'/opt/babelfish/lib',--enable-new-dtags  -L/usr/local/lib -lantlr4-runtime -lcrypto
41.18 /usr/bin/ld: src/pl_comp-2.o:/workplace/BABEL_3_1_0__PG_15_2/contrib/babelfishpg_tsql/src/pl_comp-2.c:25: multiple definition of `pltsql_curr_compile_body_lineno'; src/pl_comp.o:/workplace/BABEL_3_1_0__PG_15_2/contrib/babelfishpg_tsql/src/pl_comp.c:62: first defined here
41.78 collect2: error: ld returned 1 exit status
41.78 make: *** [/opt/babelfish/lib/postgresql/pgxs/src/makefiles/../../src/Makefile.shlib:293: babelfishpg_tsql.so] Error 1
------
Dockerfile:109
--------------------
 107 |
 108 |     WORKDIR ${PG_SRC}/contrib/babelfishpg_tsql
 109 | >>> RUN make && make PG_CONFIG=${PG_CONFIG} install
 110 |
 111 |     # Run stage
--------------------
ERROR: failed to solve: process "/bin/sh -c make && make PG_CONFIG=${PG_CONFIG} install" did not complete successfully: exit code: 2
```

**Comment by staticlibs** [comment]
It seems that `pltsql_curr_compile_body_lineno` is defined twice, I'll submit a PR for this shortly.

PS: just in case DEB packages may be useful - I have a PPA [here](https://launchpad.net/~wiltondb/+archive/ubuntu/wiltondb), DEBs there are built from modified (downstream) sources and only for Ubuntu, but should be straightforward to change to Debian and vanilla sources if needed.

PPS: not that it makes any difference here, but I suggest to use LTS `openjdk-11` or 17 instead of 9 that is long out of support.

**Comment by bachpro900** [comment]
Thanks for the answer.
I used **-fcommon** flag and worked for me:

```
# Build modified PostgreSQL for Babelfish
RUN ./configure CFLAGS="-ggdb -fcommon"\
	--prefix=${BABELFISH_HOME}/\
```

**Comment by Deepesh125** [comment]
Thank you @staticlibs for fixing this.

**Comment by Xyroid** [comment]
I tried to compile on Ubuntu 22.04 machine and docker having Ubuntu 22.04 as base image. This issue is still occurring in release [Babelfish 4.4.0 for PostgreSQL 16.6](https://github.com/babelfish-for-postgresql/babelfish-for-postgresql/releases/tag/BABEL_4_4_0__PG_16_6). The issue is fixed in `BABEL_4_6_STABLE` branch but there is no release available.

PR which fixed the issue: https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/3550/files#diff-f9d95ce4acfdb270a3ec05ba02f8645516f1f82ba1a98d43d6930fa3f994509f

Request to create new release for 4.x.
