### ISSUE TITLE
[Question] Can we connect to vanilla Postgresql RDS directly from Babelfish; and if so, how many ways exist, which is best practice

### ISSUE THREAD

**Issue by MasonJDavis** [babelfish-for-postgresql/babelfish_extensions#2191]
### What happened?

can we connect to vanilla Postgresql RDS directly from Babelfish; and if so, how many ways exist, which is best practice

### Version

BABEL_3_X_DEV (Default)

### Extension

None

### Relevant log output

```shell
none yet; looking for recommendations
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by suprio-amzn** [comment]
Yes, you can connect to the PostgreSQL standard port. Please refer to the following:

1. https://babelfishpg.org/docs/usage/command-line/#using-psql-to-connect
2. https://babelfishpg.org/docs/usage/interoperability/

**Comment by MasonJDavis** [comment]
hello,
I received a response but the response affirmed that a connection can be made in this direction

FROM "VANILLA" POSTGRESQL RDS TO BABELFISH

OR FROM SQL TO BABELFISH

My question is in regards to the REVERSE direction

can a connection be made 

FROM BABELFISH TO VANILLA POSTGRESQL RDS

**Comment by Deepesh125** [comment]
@MasonJDavis Are you looking for some sort of fdw (Foreign Data Wrapper) solution?

**Comment by MasonJDavis** [comment]
i think so

**Comment by Deepesh125** [comment]
Adding @thephantomthief for consultation.

**Comment by thephantomthief** [comment]
Hi @MasonJDavis, if I understand correctly you want to connect from Babelfish to RDS PostgreSQL.

From TDS endpoint, this is not possible because Babelfish does not support adding another PostgreSQL server as a linked server. However, you can leverage native PostgreSQL methods to query data from other PostgreSQL servers and then access this data from TDS endpoint.

You can use either [postgres_fdw](https://www.postgresql.org/docs/current/postgres-fdw.html) or [dblink](https://www.postgresql.org/docs/current/dblink.html) to import your data to Babelfish server via the PostgreSQL endpoint. 

Here is a small example where I am using dblink to fetch data from RDS PostgreSQL into my Babelfish server and then accessing the imported data from TDS endpoint:

1. Connect to the Babelfish server as the user that has sysadmin role membership and to the Babelfish database from the PG endpoint. Create the `dblink` extension.
```
psql -h localhost -U babelfish_user -d babelfish_db
psql (15.5)
Type "help" for help.

babelfish_db=# CREATE EXTENSION dblink;
CREATE EXTENSION
babelfish_db=# \dx
                                       List of installed extensions
        Name        | Version |   Schema   |                         Description                          
--------------------+---------+------------+--------------------------------------------------------------
 babelfishpg_common | 3.4.0   | public     | Transact SQL Datatype Support
 babelfishpg_tds    | 1.0.0   | public     | TDS protocol extension
 babelfishpg_tsql   | 3.5.0   | public     | Transact SQL compatibility
 dblink             | 1.2     | public     | connect to other PostgreSQL databases from within a database
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
 uuid-ossp          | 1.1     | public     | generate universally unique identifiers (UUIDs)
(6 rows)
```
2. Create a table where you want to import your data into from the RDS PostgreSQL server. In this example, I want to access the data from the `master` database when connecting via TDS endpoint so I will create the table in `master_dbo` schema. Insert the data from remote server into this table using the [dblink() function](https://www.postgresql.org/docs/current/contrib-dblink-function.html) which will execute a query in a remote database.
```
babelfish_db=# CREATE TABLE master_dbo.rds_pg_t (a int, b varchar(10));
CREATE TABLE
babelfish_db=# INSERT INTO master_dbo.rds_pg_t
	SELECT *
	FROM dblink('host=rds_pg_endpoint
				 port=5432
				 dbname=rds_pg_dbname
				 user=rds_pg_usr
				 password=rds_pg_pwd',
			    'SELECT * FROM t1')
	AS t(a int, b varchar(10));
INSERT 0 3
babelfish_db=# SELECT * FROM master_dbo.rds_pg_t;
 a |   b   
---+-------
 1 | one
 2 | two
 3 | three
(3 rows)
```

3. Additionally, you will need to GRANT SELECT privilege to `master_dbo` so that you can access this table from TDS endpoint.
```
babelfish_db=# GRANT SELECT ON master_dbo.rds_pg_t TO master_dbo;
GRANT
```

4. Connect via TDS endpoint using the same user, to the master database and you can query the same table.
```
sqlcmd -S localhost -d master -U babelfish_user -P 12345678
1> SELECT * FROM master.dbo.rds_pg_t
2> go
a           b         
----------- ----------
          1 one       
          2 two       
          3 three     

(3 rows affected)
```

**Comment by suprio-amzn** [comment]
@MasonJDavis : Does https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/2191#issuecomment-1893291526 answer your question?
