### ISSUE TITLE
[Enhancement]: Support specifying destination DB name in BabelfishDump

### ISSUE THREAD

**Issue by staticlibs** [babelfish-for-postgresql/babelfish_extensions#2267]
### What happened?

With `muti-db` mode, `bbf_dump` utility from [BabelfishDump](https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/blob/631916e85cf093e4628d6eec02552a5d2fa2efbb/BabelfishDump.spec) currently supports specifying logical DB name with `--bbf-database-name`.

With a DB like this:

```
create database test1
use test1
create table tab1(name1 nvarchar(max))
```

This logical DB name is being written into the dump output as part of schema name for all dumped objects (dump file excerpts):

```
CREATE SCHEMA test1_dbo
CREATE TABLE test1_dbo.tab1
COPY test1_dbo.tab1 (name1) FROM stdin;
```

This name is also included in dumped catalogs like `sys.babelfish_sysdatabases`.

When dump is restored with `psql` or `pg_restore` this name cannot be changed.

It would be convenient if `bbf_dump` will support additional switch like `--bbf-dest-database-name` to allow specifying different logical DB name to be written to a dump file instead of original DB name specified by `--bbf-database-name`.

For example, such new switch will allow to dump `mydb1` database from live environment as `mydb1_customer1_date1` in dump file, so the dump can be restored with this new logical DB name in dev environment.

### Version

BABEL_3_X_DEV (Default)

### Extension

None

### Which flavor of Linux are you using when you see the bug?

Fedora

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by rishabhtanwar29** [comment]
@staticlibs Thanks for pointing out this use case.

This will require following two cases to be handled to support :
1. Rename schemas and users being dumped with new database prefix, ie db1_schema1 -> db2_schema2
2. Modify catalog data being dumped to new database prefix, ie: sys.babelfish_sysdatabase, sys.babelfish_namespace_etc etc.

I have mainly two concern with this:
1. Renaming objects seems quite tricky to be handled from a frontend utility (bbf_dump/bbf_dumpall) and can be dangerous since a small bug could result in wrong catalog data or orphaned objects on the target server.
2. Renaming each objects before dumping would probably require heavily changing utility code which would take it far away from the original pg_dump/pg_dumpall utility.

I am thinking about an alternative here which is to support `sp_rename` for database in Babelfish which means that a user can rename a database and then dump it or vice-versa. The main advantage in this is that it is quite safer and convenient to perform catalog modifications and object renames in the backend compared to frontend.

Let me know what are your views on this.

**Comment by staticlibs** [comment]
Thanks for the details! I understand the concerns about long-term maintenance of `pg_dump` if such modification is added. I think that having database rename support (with `sp_rename` or `alter database modify name`), while not as flexible, will be sufficient to cover the use-case of backing up and restoring under different name. Obvious downside here is that such DB rename functionality can only be used in some future version of Babelfish, while `pg_dump`, in theory, can support this with existing old versions of Babelfish. Will close this issue as "idea rejected".
