### ISSUE TITLE
[Question]: Support of partitionning

### ISSUE THREAD

**Issue by jeanyvesauger** [babelfish-for-postgresql/babelfish_extensions#6]
### Contact Details

tivivi63@gmail.com

### What's the question?

Hello,
Nice project. What is the level of support regarding SQL Server partitionning functionality? Full or conditional?
Thanks,

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JimFinnerty** [comment]
As of the initial launch, T-SQL syntax for table partitioning was not yet supported by Babelfish.  PostgreSQL natively supports partition by hash, by range, or by a list of values, and it may be possible to define a partitioned table in the postgres dialect and then reference it from the TSQL dialect, but we don't support it because we haven't tried that specific scenario yet.  If you try it, and it does what you need, we'd love to hear how it goes.

**Comment by JimFinnerty** [comment]
In general you can create objects in the tsql dialect and query them in the postgres dialect, but creating objects in the postgres dialect and then accessing them and modifying them from the tsql dialect doesn't always work and is not supported in general.  In some cases like table partitioning it might provide a nice workaround, though, so the guidelines and limitations need to be documented.

**Comment by max-webster** [comment]
The current status can be checked at: https://babelfishpg.org/docs/usage/limitations-of-babelfish/

As of 1.2.0, the table says:

Partitioning - Table and index partitioning is not supported.	 
CREATE/ALTER/DROP PARTITION FUNCTION - This syntax is not supported.	 
CREATE/ALTER/DROP PARTITION SCHEME - This syntax is not supported.
