### ISSUE TITLE
[Question]:  Create a user such as SA ? Initialize babelfish again? sys.default_constraints? .etc

### ISSUE THREAD

**Issue by HelloWorld-9527** [babelfish-for-postgresql/babelfish_extensions#60]
### Contact Details

254980222@qq.com

### What's the question?

Hello, I am using babelfish, sometime I meet some problem.  thank you！

1. Many times I have get the "permission denied", how can I create a user such as SA in sqlserver? So that I can create database or using Profiler for tracing.
![N{UK9`FWA PJN~_H6ST7K5M](https://user-images.githubusercontent.com/23397598/150508831-ffef4ff4-bff5-4e3b-bc05-3698ed3fdc12.png)

2. if I want to change some like this, how can I initialize babelfish again?
![PHZIRL3SMJ86K}0(SEPRN@T](https://user-images.githubusercontent.com/23397598/150508849-26872a57-6129-4e65-92d2-04e3191fda94.png)

3. how can I use sys.default_constraints? the default constraint in postgres is different with other constraints like index,check. 
ALTER TABLE..CHECK CONSTRAINT is also not supported，Will these be supported in the future?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
1: your login must be a member of sysadmin role in order to create a database.
2: it is currently not possible to recreate a Babelfish database in a PG instance where this was done earlier. You have to delete the instance and create a new instance from scratch
3: The catalog sys.default_constraints is not supported in the current release of Babelfish. This will be supported in a future Babelfish release. ALTER TABLE CHECK CONSTRAINT is not currently supported, this is on the roadmap.

**Comment by suprio-amzn** [comment]
Questions have been answered.
