### ISSUE TITLE
[Question]: Will T-SQL trigger conceptual tables inserted, deleted be supported?

### ISSUE THREAD

**Issue by hanshnrch** [babelfish-for-postgresql/babelfish_extensions#63]
### Contact Details

hans-heinrich.rueter@e-velopment.de

### What's the question?

I have a question!
In SQL Server T-SQL insert, update and delete triggers access to NEW and OLD row values
are enabled by conceptual tables `inserted` and `deleted`. However in babelfish postgres
I get an error with following code:

```
create table example(id int identity not null, name varchar(255) not null)
go
create table example_archiv(id int not null, name varchar(255) not null, updated datetime not null)
go
create trigger example_trigger_archiv on example 
for INSERT, UPDATE
AS
BEGIN
    insert into example_archiv (id, name, updated)
    select inserted.id, inserted.name, getdate() from inserted
END
go
insert into example(name) values ('Hans'),('Emma'),('Charly')
update example set name = 'Franz' where name = 'Hans'
update example set name = name + '?' where id > 1
select * from example_archiv

```
In SQL Server I get the expected results in the table `example_archiv`.

In babelfish-postgresql I get an error (see below)
My question: will these two virtual tables `inserted` and `deleted` in trigger body be supported in babelfish postgresql?

### Relevant log output or information

```shell
Msg 33557097, Level 16, State 1, Line 62
relation "inserted" does not exist
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
Yes, INSERTED and DELETED are supported for FOR/AFTER triggers (DDL triggers and INSTEAD OF triggers are not currently supported). However, the current release of Babelfish contains a limitation that you cannot reference INSERTED or DELETED in a trigger that was created for multiple actions (here, INSERT and UPDATE). This issue has been fixed and will be rolled out in a future release of Babelfish. Until then, the workaround is to create a separate trigger for each action.

The error message reported above is interesting though. The error that is raised due to this issue is a different one in the current Babelfish release 1.0.0, as shown below:

1> create table example(id int identity not null, name varchar(255) not null)
2> go
1> create table example_archiv(id int not null, name varchar(255) not null, updated datetime not null)
2> go
1> create trigger example_trigger_archiv on example
2> for INSERT, UPDATE
3> AS
4> BEGIN
5>     insert into example_archiv (id, name, updated)
6>     select inserted.id, inserted.name, getdate() from inserted
7> END
8> go
Msg 33557097, Level 16, State 1, Server BABELFISH, Line 1
transition tables cannot be specified for triggers with more than one event

**Comment by hanshnrch** [comment]
Thanks a lot for your information. Version 1.0.0 is identical to current head of Branch BABEL_1_X_DEV?

**Comment by nasbyj** [comment]
@hanshnrch it is for now; we're close to formally tagging 1.0.0 as well as beginning to pull in 1.1 commits.

**Comment by robverschoor** [comment]
In v.1.1.0, the restriction that a multi-action DML trigger cannot references its transition tables, has been resolved.
