### ISSUE TITLE
Permissions Management for new users inside Babelfish

### ISSUE THREAD

**Issue by npo38** [babelfish-for-postgresql/babelfish_extensions#67]
### Contact Details

nporte@protonmail.com

### What's the question?

Hi,

I'm using Babelfish wih AWS RDS Aurora. It's working great but I have a question regarding permissions. For the moment, when you create a new user, only sysadmin role can be assigned, which is not very secure.

Are there some updates planned ? For example, for fine grained role, or to assign db_owner role for a user ? Or a workaround which can be compliant in terms of security ?

The answer is important because I have some SQL server databases on prem to migrate.

Thanks for your help.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robverschoor** [comment]
GRANT and REVOKE, as well as the T-SQL database principal ("DB user") concept are not currently implemented in Babelfish (this is on the roadmap). Currently, this means a T-SQL login needs to have sysadmin role in order to be able to create databases or objects in those databases. Non-sysadmin logins currently can only access tempdb and master (as 'guest'), and can only create #temp tables.  
Work is in progress on building out  database principal  and permissions in Babelfish.

**Comment by suprio-amzn** [comment]
A majority of the functionality required for fine-grained authorizations for the Database securable using Database-level users is now available in the Babelfish 2.1.0 release.
